import { useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { CheckCircle2, ShieldAlert } from 'lucide-react'
import { api } from '../api/client'
import type { AuditRecordList, AuditVerification, Tenant } from '../api/types'
import { StatusBadge } from '../components/StatusBadge'
import { ErrorState, LoadingState } from '../components/PageState'

export function AuditPage(){const [tenant,setTenant]=useState('');const tenants=useQuery({queryKey:['tenants'],queryFn:()=>api.get<Tenant[]>('/tenants')});const verify=useQuery({queryKey:['audit','verify',tenant],queryFn:()=>api.get<AuditVerification>(`/audit/verify${api.query({tenant_id:tenant})}`)});const records=useQuery({queryKey:['audit','records',tenant],queryFn:()=>api.get<AuditRecordList>(`/audit/records${api.query({tenant_id:tenant,limit:100})}`)});return <div className="stack"><section className="audit-banner"><div className={verify.data?.valid?'audit-icon audit-icon--ok':'audit-icon audit-icon--bad'}>{verify.data?.valid?<CheckCircle2/>:<ShieldAlert/>}</div><div><span>Integridad de cadena</span><strong>{verify.isLoading?'Verificando…':verify.data?.valid?'Cadena íntegra':'Requiere revisión'}</strong><p>{verify.data?`${verify.data.record_count} registros · secuencia ${verify.data.last_sequence}`:'Validación criptográfica del audit trail.'}</p></div><select value={tenant} onChange={e=>setTenant(e.target.value)}><option value="">Plataforma</option>{tenants.data?.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></section><section className="section section--flush">{records.isLoading?<LoadingState/>:records.error?<ErrorState message={(records.error as Error).message}/>:<div className="table-wrap"><table><thead><tr><th>Sec.</th><th>Acción</th><th>Recurso</th><th>Origen</th><th>Resultado</th><th>Fecha</th></tr></thead><tbody>{records.data?.items.map(r=><tr key={r.id}><td>{r.sequence}</td><td><strong>{r.action}</strong><small>{r.actor_type}{r.actor_user_id?` · ${r.actor_user_id.slice(0,8)}…`:''}</small></td><td>{r.resource_type}<small>{r.resource_id?.slice(0,8)??'—'}</small></td><td>{r.source_service}</td><td><StatusBadge value={r.outcome}/></td><td>{new Date(r.occurred_at).toLocaleString()}</td></tr>)}</tbody></table></div>}</section></div>}
