import { useMemo, useState, type FormEvent } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Copy, KeyRound, Plus, X } from 'lucide-react'
import { api } from '../api/client'
import type { Asset, Enrollment, EnrollmentToken, Tenant } from '../api/types'
import { StatusBadge } from '../components/StatusBadge'
import { EmptyState, ErrorState, LoadingState } from '../components/PageState'

export function EnrollmentPage(){
 const qc=useQueryClient();const [tenant,setTenant]=useState('');const [asset,setAsset]=useState('');const [minutes,setMinutes]=useState(60);const [rawToken,setRawToken]=useState<string|null>(null)
 const tenants=useQuery({queryKey:['tenants'],queryFn:()=>api.get<Tenant[]>('/tenants')});const assets=useQuery({queryKey:['assets'],queryFn:()=>api.get<Asset[]>('/assets')});const tokens=useQuery({queryKey:['enrollment-tokens'],queryFn:()=>api.get<EnrollmentToken[]>('/enrollment-tokens')});const enrollments=useQuery({queryKey:['enrollments'],queryFn:()=>api.get<Enrollment[]>('/enrollments')})
 const filtered=useMemo(()=>assets.data?.filter(a=>!tenant||a.tenant_id===tenant)??[],[assets.data,tenant])
 const create=useMutation({mutationFn:()=>api.post<EnrollmentToken>('/enrollment-tokens',{tenant_id:tenant,asset_id:asset,expires_in_minutes:minutes}),onSuccess:(data)=>{setRawToken(data.token??null);qc.invalidateQueries({queryKey:['enrollment-tokens']})}});const revoke=useMutation({mutationFn:(id:string)=>api.post<EnrollmentToken>(`/enrollment-tokens/${id}/revoke`),onSuccess:()=>qc.invalidateQueries({queryKey:['enrollment-tokens']})})
 function submit(e:FormEvent){e.preventDefault();void create.mutateAsync()}
 return <div className="stack"><section className="section"><div className="section-heading"><div><span className="section-icon"><KeyRound size={17}/></span><div><h2>Token de enrollment</h2><p>Credencial de un solo uso para registrar un endpoint.</p></div></div></div>{rawToken&&<div className="secret-reveal"><div><strong>Token recién creado</strong><p>Se muestra únicamente en esta sesión de pantalla. Cópialo antes de cerrar.</p><code>{rawToken}</code></div><div><button className="icon-button" onClick={()=>void navigator.clipboard.writeText(rawToken)} aria-label="Copiar"><Copy size={18}/></button><button className="icon-button" onClick={()=>setRawToken(null)} aria-label="Ocultar"><X size={18}/></button></div></div>}<form className="inline-form" onSubmit={submit}><label>Empresa<select required value={tenant} onChange={e=>{setTenant(e.target.value);setAsset('')}}><option value="">Seleccione…</option>{tenants.data?.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label>Activo<select required value={asset} onChange={e=>setAsset(e.target.value)}><option value="">Seleccione…</option>{filtered.map(a=><option key={a.guardian_asset_id} value={a.guardian_asset_id}>{a.display_name}</option>)}</select></label><label>Vigencia (min)<input type="number" min={5} max={1440} value={minutes} onChange={e=>setMinutes(Number(e.target.value))}/></label><button className="button button--primary" disabled={create.isPending}><Plus size={16}/>Crear token</button></form></section><section className="section"><div className="section-heading"><div><h2>Tokens emitidos</h2><p>El valor completo nunca se persiste en la interfaz.</p></div></div>{tokens.isLoading?<LoadingState/>:tokens.error?<ErrorState message={(tokens.error as Error).message}/>:tokens.data?.length?<div className="table-wrap"><table><thead><tr><th>Hint</th><th>Activo</th><th>Estado</th><th>Expira</th><th></th></tr></thead><tbody>{tokens.data.map(t=><tr key={t.id}><td><code>{t.token_hint}</code></td><td>{t.asset_id.slice(0,8)}…</td><td><StatusBadge value={t.status}/></td><td>{new Date(t.expires_at).toLocaleString()}</td><td>{!['revoked','consumed'].includes(t.status)&&<button className="button button--ghost" onClick={()=>revoke.mutate(t.id)}>Revocar</button>}</td></tr>)}</tbody></table></div>:<EmptyState title="Sin tokens" body="Crea un token para registrar un agente."/>}</section><section className="section"><div className="section-heading"><div><h2>Enrollments</h2><p>Dispositivos registrados y estado de certificado.</p></div></div>{enrollments.data?.length?<div className="table-wrap"><table><thead><tr><th>Hostname</th><th>Plataforma</th><th>Estado</th><th>Dispositivo</th></tr></thead><tbody>{enrollments.data.map(e=><tr key={e.device_id}><td>{e.hostname}</td><td>{e.platform}</td><td><StatusBadge value={e.status}/></td><td>{e.device_id.slice(0,8)}…</td></tr>)}</tbody></table></div>:<EmptyState title="Sin enrollments" body="Los equipos registrados aparecerán aquí."/>}</section></div>
}
