import { useState, type FormEvent } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { api } from '../api/client'
import type { Department, Membership, Tenant } from '../api/types'
import { useSession } from '../session/SessionContext'
import { useTenantScope } from '../scope/TenantScopeContext'
import { StatusBadge } from '../components/StatusBadge'
import { EmptyState, ErrorState, LoadingState } from '../components/PageState'

export function OrganizationPage(){
 const {user}=useSession();const scope=useTenantScope();const qc=useQueryClient();const selected=scope.tenantId;const [name,setName]=useState('');const [slug,setSlug]=useState('')
 const departments=useQuery({queryKey:['departments',selected],queryFn:()=>api.get<Department[]>(`/tenants/${selected}/departments`),enabled:!!selected});const memberships=useQuery({queryKey:['memberships',selected],queryFn:()=>api.get<Membership[]>(`/tenants/${selected}/memberships`),enabled:!!selected,retry:false});const create=useMutation({mutationFn:()=>api.post<Tenant>('/tenants',{name,slug,timezone:'America/Tegucigalpa',locale:'es-HN'}),onSuccess:(tenant)=>{qc.invalidateQueries({queryKey:['scope','tenants']});scope.setTenantId(tenant.id);setName('');setSlug('')}})
 function submit(e:FormEvent){e.preventDefault();void create.mutateAsync()}
 if(scope.loading)return <LoadingState/>;if(scope.error)return <ErrorState message={scope.error.message}/>
 return <div className="organization-layout"><aside className="tenant-list"><div className="tenant-list-head"><strong>Empresas</strong><span>{scope.tenants.length}</span></div>{scope.tenants.map(t=><button key={t.id} className={selected===t.id?'tenant-row tenant-row--active':'tenant-row'} onClick={()=>scope.setTenantId(t.id)}><div><strong>{t.name}</strong><span>{t.slug}</span></div><StatusBadge value={t.status}/></button>)}{user?.role==='platform_admin'&&<form className="tenant-create" onSubmit={submit}><strong>Nueva empresa</strong><input required placeholder="Nombre" value={name} onChange={e=>setName(e.target.value)}/><input required placeholder="slug-empresa" value={slug} onChange={e=>setSlug(e.target.value.toLowerCase())}/><button className="button button--primary" disabled={create.isPending}>Crear</button>{create.error&&<p className="form-error">{(create.error as Error).message}</p>}</form>}</aside>{selected?<div className="stack"><section className="section"><div className="section-heading"><div><h2>Sedes</h2><p>Estructura física de la empresa seleccionada.</p></div></div>{scope.sites.length?<div className="simple-list">{scope.sites.map(s=><div key={s.id}><div><strong>{s.code}</strong><span>{s.name}{s.city?` · ${s.city}`:''}</span></div><StatusBadge value={s.status}/></div>)}</div>:<EmptyState title="Sin sedes" body="No hay sedes visibles para esta empresa."/>}</section><section className="section"><div className="section-heading"><div><h2>Departamentos</h2><p>Jerarquía organizacional.</p></div></div>{departments.isLoading?<LoadingState/>:departments.error?<ErrorState message={(departments.error as Error).message}/>:departments.data?.length?<div className="simple-list">{departments.data.map(d=><div key={d.id}><div><strong>{d.code}</strong><span>{d.name}</span></div><StatusBadge value={d.status}/></div>)}</div>:<EmptyState title="Sin departamentos" body="No hay departamentos visibles."/>}</section><section className="section"><div className="section-heading"><div><h2>Membresías</h2><p>Acceso y rol dentro de la empresa.</p></div></div>{memberships.error?<p className="muted">Tu rol no permite consultar las membresías de esta empresa.</p>:memberships.isLoading?<LoadingState/>:memberships.data?.length?<div className="simple-list">{memberships.data.map(m=><div key={m.id}><div><strong>{m.user_id.slice(0,8)}…</strong><span>{m.role}</span></div><StatusBadge value={m.is_active?'active':'disabled'}/></div>)}</div>:<EmptyState title="Sin membresías" body="No hay membresías visibles."/>}</section></div>:<EmptyState title="Sin empresa seleccionada" body="Crea o selecciona una empresa para administrar su estructura."/>}</div>
}
