import { useEffect, useState, type FormEvent } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { api } from '../api/client'
import type { Department, Membership, Site, Tenant } from '../api/types'
import { useSession } from '../session/SessionContext'
import { StatusBadge } from '../components/StatusBadge'
import { EmptyState, ErrorState, LoadingState } from '../components/PageState'

export function OrganizationPage(){
 const {user}=useSession();const qc=useQueryClient();const tenants=useQuery({queryKey:['tenants'],queryFn:()=>api.get<Tenant[]>('/tenants')});const [selected,setSelected]=useState('');const [name,setName]=useState('');const [slug,setSlug]=useState('');useEffect(()=>{if(!selected&&tenants.data?.[0])setSelected(tenants.data[0].id)},[tenants.data,selected])
 const sites=useQuery({queryKey:['sites',selected],queryFn:()=>api.get<Site[]>(`/tenants/${selected}/sites`),enabled:!!selected});const departments=useQuery({queryKey:['departments',selected],queryFn:()=>api.get<Department[]>(`/tenants/${selected}/departments`),enabled:!!selected});const memberships=useQuery({queryKey:['memberships',selected],queryFn:()=>api.get<Membership[]>(`/tenants/${selected}/memberships`),enabled:!!selected,retry:false});const create=useMutation({mutationFn:()=>api.post<Tenant>('/tenants',{name,slug,timezone:'America/Tegucigalpa',locale:'es-HN'}),onSuccess:(tenant)=>{qc.invalidateQueries({queryKey:['tenants']});setSelected(tenant.id);setName('');setSlug('')}})
 function submit(e:FormEvent){e.preventDefault();void create.mutateAsync()}
 if(tenants.isLoading)return <LoadingState/>;if(tenants.error)return <ErrorState message={(tenants.error as Error).message}/>
 return <div className="organization-layout"><aside className="tenant-list"><div className="tenant-list-head"><strong>Empresas</strong><span>{tenants.data?.length??0}</span></div>{tenants.data?.map(t=><button key={t.id} className={selected===t.id?'tenant-row tenant-row--active':'tenant-row'} onClick={()=>setSelected(t.id)}><div><strong>{t.name}</strong><span>{t.slug}</span></div><StatusBadge value={t.status}/></button>)}{user?.role==='platform_admin'&&<form className="tenant-create" onSubmit={submit}><strong>Nueva empresa</strong><input required placeholder="Nombre" value={name} onChange={e=>setName(e.target.value)}/><input required placeholder="slug-empresa" value={slug} onChange={e=>setSlug(e.target.value.toLowerCase())}/><button className="button button--primary">Crear</button></form>}</aside><div className="stack"><section className="section"><div className="section-heading"><div><h2>Sedes</h2><p>Estructura física del tenant seleccionado.</p></div></div>{sites.data?.length?<div className="simple-list">{sites.data.map(s=><div key={s.id}><div><strong>{s.code}</strong><span>{s.name}{s.city?` · ${s.city}`:''}</span></div><StatusBadge value={s.status}/></div>)}</div>:<EmptyState title="Sin sedes" body="No hay sedes visibles para esta empresa."/>}</section><section className="section"><div className="section-heading"><div><h2>Departamentos</h2><p>Jerarquía organizacional.</p></div></div>{departments.data?.length?<div className="simple-list">{departments.data.map(d=><div key={d.id}><div><strong>{d.code}</strong><span>{d.name}</span></div><StatusBadge value={d.status}/></div>)}</div>:<EmptyState title="Sin departamentos" body="No hay departamentos visibles."/>}</section><section className="section"><div className="section-heading"><div><h2>Membresías</h2><p>Acceso y rol dentro de la empresa.</p></div></div>{memberships.error?<p className="muted">Tu rol no permite consultar las membresías de esta empresa.</p>:memberships.data?.length?<div className="simple-list">{memberships.data.map(m=><div key={m.id}><div><strong>{m.user_id.slice(0,8)}…</strong><span>{m.role}</span></div><StatusBadge value={m.is_active?'active':'disabled'}/></div>)}</div>:<EmptyState title="Sin membresías" body="No hay membresías visibles."/>}</section></div></div>
}
