import { useState, type FormEvent } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Plus } from 'lucide-react'
import { api } from '../api/client'
import type { Role, User } from '../api/types'
import { useSession } from '../session/SessionContext'
import { StatusBadge } from '../components/StatusBadge'
import { ErrorState, LoadingState } from '../components/PageState'

const roles:Role[]=['platform_admin','org_admin','security_admin','it_operator','helpdesk','auditor','viewer']
export function UsersPage(){const {user}=useSession();const qc=useQueryClient();const [show,setShow]=useState(false);const [email,setEmail]=useState('');const [display,setDisplay]=useState('');const [password,setPassword]=useState('');const [role,setRole]=useState<Role>('viewer');const users=useQuery({queryKey:['users'],queryFn:()=>api.get<User[]>('/users'),retry:false});const create=useMutation({mutationFn:()=>api.post<User>('/users',{email,display_name:display,password,role}),onSuccess:()=>{qc.invalidateQueries({queryKey:['users']});setShow(false);setPassword('')}});const status=useMutation({mutationFn:(input:{id:string;active:boolean})=>api.patch<User>(`/users/${input.id}/status`,{is_active:input.active}),onSuccess:()=>qc.invalidateQueries({queryKey:['users']})});function submit(e:FormEvent){e.preventDefault();void create.mutateAsync()}if(users.isLoading)return <LoadingState/>;if(users.error)return <ErrorState message="Tu rol no permite consultar el directorio de usuarios."/>;return <section className="section section--flush"><div className="toolbar"><div><strong>Directorio de acceso</strong><span className="muted"> Identity Service</span></div>{user?.role==='platform_admin'&&<button className="button button--primary" onClick={()=>setShow(!show)}><Plus size={16}/>Nuevo usuario</button>}</div>{show&&<form className="inline-form" onSubmit={submit}><label>Nombre<input required value={display} onChange={e=>setDisplay(e.target.value)}/></label><label>Correo<input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Contraseña<input type="password" minLength={12} required value={password} onChange={e=>setPassword(e.target.value)}/></label><label>Rol<select value={role} onChange={e=>setRole(e.target.value as Role)}>{roles.map(r=><option key={r}>{r}</option>)}</select></label><button className="button button--primary">Crear</button></form>}<div className="table-wrap"><table><thead><tr><th>Usuario</th><th>Rol global</th><th>Estado</th><th></th></tr></thead><tbody>{users.data?.map(item=><tr key={item.id}><td><strong>{item.display_name}</strong><small>{item.email}</small></td><td>{item.role}</td><td><StatusBadge value={item.is_active?'active':'disabled'}/></td><td>{user?.role==='platform_admin'&&item.id!==user.id&&<button className="button button--ghost" onClick={()=>status.mutate({id:item.id,active:!item.is_active})}>{item.is_active?'Desactivar':'Activar'}</button>}</td></tr>)}</tbody></table></div></section>}
