from alembic import op
import sqlalchemy as sa
revision="20260827_0001";down_revision=None;branch_labels=None;depends_on=None
def upgrade():
 op.create_table("commands",sa.Column("command_id",sa.Uuid(),primary_key=True),sa.Column("tenant_id",sa.Uuid(),nullable=False),sa.Column("guardian_asset_id",sa.Uuid(),nullable=False),sa.Column("device_id",sa.Uuid(),nullable=False),sa.Column("created_by",sa.Uuid(),nullable=False),sa.Column("command_type",sa.String(64),nullable=False),sa.Column("arguments",sa.JSON(),nullable=False),sa.Column("idempotency_key",sa.String(128),nullable=False),sa.Column("request_digest",sa.String(64),nullable=False),sa.Column("state",sa.String(16),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("expires_at",sa.DateTime(timezone=True),nullable=False),sa.Column("dispatch_attempts",sa.Integer(),nullable=False),sa.Column("execution_token_hash",sa.String(64)),sa.Column("lease_expires_at",sa.DateTime(timezone=True)),sa.UniqueConstraint("tenant_id","idempotency_key",name="uq_commands_tenant_idempotency"))
 op.create_index("ix_commands_tenant_id","commands",["tenant_id"]);op.create_index("ix_commands_guardian_asset_id","commands",["guardian_asset_id"]);op.create_index("ix_commands_device_id","commands",["device_id"])
 op.create_table("command_results",sa.Column("result_id",sa.Uuid(),primary_key=True),sa.Column("command_id",sa.Uuid(),sa.ForeignKey("commands.command_id",ondelete="CASCADE"),nullable=False),sa.Column("result_sequence",sa.Integer(),nullable=False),sa.Column("status",sa.String(16),nullable=False),sa.Column("exit_code",sa.Integer()),sa.Column("summary",sa.String(2048),nullable=False),sa.Column("started_at",sa.DateTime(timezone=True),nullable=False),sa.Column("finished_at",sa.DateTime(timezone=True),nullable=False),sa.Column("payload_digest",sa.String(64),nullable=False),sa.Column("received_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("command_id","result_sequence",name="uq_command_result_sequence"));op.create_index("ix_command_results_command_id","command_results",["command_id"])
 op.create_table("outbox_events",sa.Column("event_id",sa.Uuid(),primary_key=True),sa.Column("subject",sa.String(256),nullable=False),sa.Column("aggregate_id",sa.String(128),nullable=False),sa.Column("payload",sa.JSON(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("published_at",sa.DateTime(timezone=True)),sa.Column("attempts",sa.Integer(),nullable=False),sa.Column("last_error",sa.String(512)));op.create_index("ix_outbox_events_subject","outbox_events",["subject"])
def downgrade():op.drop_table("outbox_events");op.drop_table("command_results");op.drop_table("commands")
